name: Automatic GitHub Release
description: Automatic GitHub release when the package.json version changes
branding:
  color: blue
  icon: archive
inputs:
  token:
    description: Personal access token. Defaults to GITHUB_TOKEN.
    default: ${{ github.token }}
    required: false
runs:
  using: 'node12'
  main: 'main.js'