name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      # - run: apt-get update && apt-get install -y git # Images used by nektos/act don't have git preinstalled
      - uses: ./